package com.logics.sierra_book.ST_ch2._2;

/*-
	@created 18-07-2020

	What is the result?
		x - BD
		x - DB
		x - BDC
		x - DBC
	v - Compilation fails

	"The implied super() call in Bottom2's constructor cannot be staisfied because there is no no-arg constructor in Top. A default, no-arg constructor is generated by the compiler only if the class has no constructor defined explicitly."
*/

class Top {
	public Top(String s) { System.out.print("B"); }
}
public class Bottom2 extends Top {
	public Bottom2(String s) { System.out.print("D"); }
	public static void main(String [] args) {
		new Bottom2("C");
		System.out.println(" ");
	}
}

/*- COMPILATION ERROR

	com/logics/sierra_book/ST_ch2/_2/Bottom2.java:11: error: constructor Top in class Top cannot be applied to given types;
		public Bottom2(String s) { System.out.print("D"); }
			                 ^
	  required: String
	  found: no arguments
	  reason: actual and formal argument lists differ in length
	1 error

*/
